version: '3'

services:
   app:
      build: .
      volumes:
        - ./knack/.env.js:/app/.env.js
        - ./knack/src:/app/src
        - ./knack/dist:/app/dist
        - ./knack/server.js:/app/server.js
        - ./knack/routes.js:/app/routes.js
        - ./knack/webpack.config.js:/app/webpack.config.js
        - ./knack/base.webpack.config.js:/app/base.webpack.config.js
        - ./knack/dev.webpack.config.js:/app/dev.webpack.config.js
      ports:
         - "3000:3000"
